FROM ubuntu:18.04

RUN mkdir -p /build \
  && apt-get update \
  && apt-get install -y debhelper dh-make devscripts gnupg2 vim rsync
RUN mkdir -p -m700 /root/.gnupg

RUN apt-get install -y build-essential bison ruby rake git pkg-config libssl-dev
